# Generated by Django 5.2.8 on 2025-11-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_refrigerated',
            field=models.BooleanField(default=False, help_text='If true, this Section is temperature-controlled (refrigerated) and can store perishable items.'),
        ),
    ]
