# Generated by Django 5.2.8 on 2025-12-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_drop_warehouseuser"),
    ]

    operations = [
        # The legacy table was already dropped by a previous migration
        # (0003_drop_warehouseuser). The auto-generated DeleteModel would
        # attempt to drop the table again and fail. Use a safe SQL that
        # drops the table if it exists (idempotent) and mark the migration
        # as applied.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS core_warehouseuser;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
