# Generated by Django 5.2.8 on 2025-12-08 00:08

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_number', models.CharField(max_length=100, unique=True)),
                ('doc_type', models.IntegerField(choices=[(orders.models.Document.DocType['OUTBOUND_ORDER'], 'Outbound Order'), (orders.models.Document.DocType['TRANSFER_ORDER'], 'Transfer Order'), (orders.models.Document.DocType['INBOUND_RECEIPT'], 'Inbound Receipt'), (orders.models.Document.DocType['ADJUSTMENT'], 'Adjustment')], default=orders.models.Document.DocType['OUTBOUND_ORDER'])),
                ('status', models.IntegerField(choices=[(orders.models.Document.Status['DRAFT'], 'Draft'), (orders.models.Document.Status['PENDING'], 'Pending'), (orders.models.Document.Status['PARTIALLY_ALLOCATED'], 'Partially Allocated'), (orders.models.Document.Status['FULLY_ALLOCATED'], 'Fully Allocated'), (orders.models.Document.Status['PARTIALLY_PICKED'], 'Partially Picked'), (orders.models.Document.Status['FULLY_PICKED'], 'Fully Picked'), (orders.models.Document.Status['COMPLETED'], 'Completed'), (orders.models.Document.Status['CANCELED'], 'Canceled')], default=orders.models.Document.Status['DRAFT'])),
                ('erp_doc_number', models.CharField(blank=True, help_text='External ERP reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Company that owns/controls this document', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to='core.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, help_text='For transfer orders: destination warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_documents_to', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_requested', models.PositiveIntegerField()),
                ('qty_allocated', models.PositiveIntegerField(default=0)),
                ('qty_picked', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.document')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'verbose_name': 'Document Line',
                'verbose_name_plural': 'Document Lines',
                'ordering': ['document', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField()),
                ('qty_picked', models.PositiveIntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.documentline')),
                ('quant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.quant')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['line', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_number'], name='orders_docu_doc_num_d1c435_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='orders_docu_status_e062cc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['warehouse', 'status'], name='orders_docu_warehou_526f62_idx'),
        ),
    ]
