# Generated by Django 5.2.8 on 2026-03-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_number', models.CharField(blank=True, help_text='Attempted doc_number', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success (fully allocated)'), ('PARTIAL', 'Partial (some lines unallocated)'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('allocation_results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, help_text='Created document (null if creation itself failed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilment_logs', to='orders.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilment_logs', to='core.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fulfilment Log',
                'verbose_name_plural': 'Fulfilment Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='orders_fulf_owner_i_ab1dc7_idx'), models.Index(fields=['status'], name='orders_fulf_status_815354_idx')],
            },
        ),
    ]
