# Generated by Django 5.2.8 on 2025-12-08 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('code', models.CharField(choices=[('UNRESTRICTED', 'Unrestricted'), ('BLOCKED', 'Blocked'), ('QUALITY_CHECK', 'Quality Check'), ('CONSIGNMENT', 'Consignment')], max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('length_mm', models.PositiveIntegerField(default=0)),
                ('width_mm', models.PositiveIntegerField(default=0)),
                ('height_mm', models.PositiveIntegerField(default=0)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('fragile', models.BooleanField(default=False)),
                ('hazardous', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False, help_text='True if this item must be stored in a refrigerated section/bin')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.item')),
            ],
            options={
                'ordering': ['item', 'lot_code'],
                'unique_together': {('item', 'lot_code')},
            },
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty_reserved', models.PositiveIntegerField(default=0)),
                ('is_temp_unrefrigerated', models.BooleanField(default=False, help_text='Temporarily stored refrigerated item in non-refrigerated section')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='core.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quants', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quants', to='inventory.lot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='core.company')),
                ('stock_category', models.ForeignKey(default='UNRESTRICTED', on_delete=django.db.models.deletion.PROTECT, to='inventory.stockcategory')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Goods In'), ('RESERVED', 'Reserved'), ('OUTBOUND', 'Goods Out'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
                ('from_quant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.quant')),
                ('to_quant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.quant')),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='inventory_m_item_id_41b3d8_idx'), models.Index(fields=['warehouse', '-created_at'], name='inventory_m_warehou_674c04_idx'), models.Index(fields=['-created_at'], name='inventory_m_created_c80df3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['item', 'bin'], name='inventory_q_item_id_00a926_idx'),
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['item', 'owner'], name='inventory_q_item_id_e91bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['bin'], name='inventory_q_bin_id_74d0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['stock_category'], name='inventory_q_stock_c_22c99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quant',
            unique_together={('item', 'bin', 'lot', 'stock_category', 'owner')},
        ),
    ]
