# Generated by Django 5.2.8 on 2025-11-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_refrigeration',
            field=models.BooleanField(default=False, help_text='True if this item must be stored in a refrigerated section/bin'),
        ),
        migrations.AddField(
            model_name='quant',
            name='is_temp_unrefrigerated',
            field=models.BooleanField(default=False, help_text='Temporarily stored refrigerated item in non-refrigerated section'),
        ),
    ]
