# Generated by Django 5.2.8 on 2026-03-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcategory',
            name='allocatable',
            field=models.BooleanField(default=True, help_text='Whether stock in this category can be allocated to orders.'),
        ),
        migrations.AlterField(
            model_name='stockcategory',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
