# Generated by Django 5.2.8 on 2026-03-05 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event_types', models.JSONField(default=list, help_text='JSON list, e.g. ["fulfil.success","fulfil.partial","fulfil.failed"]')),
                ('active', models.BooleanField(default=True)),
                ('secret', models.CharField(blank=True, help_text='Optional HMAC-SHA256 secret.  Signature sent as X-WMS-Signature header.', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Webhook',
                'verbose_name_plural': 'Company Webhooks',
            },
        ),
    ]
