# Generated by Django 5.2.8 on 2025-12-08 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('inbound_secret', models.CharField(blank=True, max_length=200)),
                ('outbound_base_url', models.URLField(blank=True)),
                ('outbound_auth_token', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_integrations', to='core.company')),
            ],
            options={
                'verbose_name': 'ERP Integration',
                'verbose_name_plural': 'ERP Integrations',
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='erp_connector.erpintegration')),
            ],
            options={
                'verbose_name': 'Inbound Event',
                'verbose_name_plural': 'Inbound Events',
                'indexes': [models.Index(fields=['integration', 'event_id'], name='erp_connect_integra_e60bd0_idx')],
            },
        ),
    ]
