# Generated by Django 5.2.8 on 2026-03-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('erp_connector', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpintegration',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, help_text='Used when a pulled order does not specify a warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_integrations', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='erpintegration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
